use std::fs;
use std::path::PathBuf;
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

#[cfg(target_os = "linux")]
use std::hash::{Hash, Hasher};
#[cfg(target_os = "linux")]
use std::os::unix::fs::{symlink, PermissionsExt};

fn fixture_dir(name: &str) -> PathBuf {
    let stamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system time should be after Unix epoch")
        .as_nanos();
    let dir = std::env::temp_dir().join(format!("mdo-test-{name}-{}-{stamp}", std::process::id()));
    fs::create_dir_all(&dir).expect("failed to create temp fixture dir");
    dir
}

#[test]
fn converts_markdown_to_styled_html5_document() {
    let dir = fixture_dir("html5");
    let input = dir.join("sample.md");
    fs::write(
        &input,
        "# Sample Title\n\nA paragraph with **strong** text.\n\n| A | B |\n|---|---|\n| 1 | 2 |\n",
    )
    .expect("failed to write markdown fixture");

    let output = Command::new(env!("CARGO_BIN_EXE_mdo"))
        .arg(&input)
        .output()
        .expect("failed to run mdo");

    assert!(output.status.success(), "mdo failed: {output:?}");

    let html = fs::read_to_string(dir.join("sample.html")).expect("failed to read html output");
    assert!(html.contains("<!DOCTYPE html>"));
    assert!(html.contains("<title>Sample Title</title>"));
    assert!(html.contains("<h1>Sample Title</h1>"));
    assert!(html.contains("<strong>strong</strong>"));
    assert!(html.contains("<table>"));
    assert!(html.contains("#theme-toggle"));
    assert!(html.contains(&format!(
        "<meta name=\"generator\" content=\"mdo {}\">",
        env!("CARGO_PKG_VERSION")
    )));
    assert!(html.contains(&format!(
        "Generated by <a href=\"{}\">mdo</a> {} in ",
        env!("CARGO_PKG_HOMEPAGE"),
        env!("CARGO_PKG_VERSION")
    )));
    assert!(html.contains("<time datetime=\""));
    assert!(html.contains("</time>."));

    fs::remove_dir_all(dir).expect("failed to clean up temp fixture dir");
}

#[test]
fn bare_output_omits_document_shell() {
    let dir = fixture_dir("bare");
    let input = dir.join("fragment.md");
    let output_path = dir.join("fragment.html");
    fs::write(&input, "**bare** fragment").expect("failed to write markdown fixture");

    let output = Command::new(env!("CARGO_BIN_EXE_mdo"))
        .args(["--bare", "--output"])
        .arg(&output_path)
        .arg(&input)
        .output()
        .expect("failed to run mdo");

    assert!(output.status.success(), "mdo failed: {output:?}");

    let html = fs::read_to_string(output_path).expect("failed to read html output");
    assert!(html.contains("<p><strong>bare</strong> fragment</p>"));
    assert!(!html.contains("<!DOCTYPE html>"));
    assert!(!html.contains("<html"));
    assert!(!html.contains("<style>"));
    assert!(!html.contains("name=\"generator\""));
    assert!(!html.contains("Generated by <a"));

    fs::remove_dir_all(dir).expect("failed to clean up temp fixture dir");
}

#[test]
fn sanitizes_active_html_by_default() {
    let dir = fixture_dir("sanitize");
    let input = dir.join("payload.md");
    let output_path = dir.join("payload.html");
    fs::write(
        &input,
        "# Payload\n\n<script>window.__mdo_xss=1</script>\n\n<img src=x onerror=\"window.__mdo_img=1\">\n",
    )
    .expect("failed to write markdown fixture");

    let output = Command::new(env!("CARGO_BIN_EXE_mdo"))
        .args(["--bare", "--output"])
        .arg(&output_path)
        .arg(&input)
        .output()
        .expect("failed to run mdo");

    assert!(output.status.success(), "mdo failed: {output:?}");

    let html = fs::read_to_string(output_path).expect("failed to read html output");
    assert!(html.contains("<h1>Payload</h1>"));
    assert!(!html.contains("<script>"));
    assert!(!html.contains("window.__mdo_xss"));
    assert!(!html.contains("onerror"));
    assert!(html.contains("<img src=\"x\">"));

    fs::remove_dir_all(dir).expect("failed to clean up temp fixture dir");
}

#[test]
fn unsafe_html_preserves_raw_html() {
    let dir = fixture_dir("unsafe-html");
    let input = dir.join("payload.md");
    let output_path = dir.join("payload.html");
    fs::write(
        &input,
        "# Payload\n\n<script>window.__mdo_xss=1</script>\n\n<img src=x onerror=\"window.__mdo_img=1\">\n",
    )
    .expect("failed to write markdown fixture");

    let output = Command::new(env!("CARGO_BIN_EXE_mdo"))
        .args(["--unsafe-html", "--bare", "--output"])
        .arg(&output_path)
        .arg(&input)
        .output()
        .expect("failed to run mdo");

    assert!(output.status.success(), "mdo failed: {output:?}");

    let html = fs::read_to_string(output_path).expect("failed to read html output");
    assert!(html.contains("<script>window.__mdo_xss=1</script>"));
    assert!(html.contains("onerror=\"window.__mdo_img=1\""));

    fs::remove_dir_all(dir).expect("failed to clean up temp fixture dir");
}

#[test]
fn sanitizer_keeps_markdown_task_list_checkboxes() {
    let dir = fixture_dir("task-list");
    let input = dir.join("tasks.md");
    let output_path = dir.join("tasks.html");
    fs::write(&input, "- [ ] unchecked\n- [x] checked\n")
        .expect("failed to write markdown fixture");

    let output = Command::new(env!("CARGO_BIN_EXE_mdo"))
        .args(["--bare", "--output"])
        .arg(&output_path)
        .arg(&input)
        .output()
        .expect("failed to run mdo");

    assert!(output.status.success(), "mdo failed: {output:?}");

    let html = fs::read_to_string(output_path).expect("failed to read html output");
    assert!(html.contains(r#"<input type="checkbox" disabled="">"#));
    assert!(html.contains(r#"<input type="checkbox" checked="" disabled="">"#));

    fs::remove_dir_all(dir).expect("failed to clean up temp fixture dir");
}

#[test]
fn sanitizer_keeps_markdown_footnote_links() {
    let dir = fixture_dir("footnotes");
    let input = dir.join("notes.md");
    let output_path = dir.join("notes.html");
    fs::write(&input, "A footnote ref[^1].\n\n[^1]: Footnote text.\n")
        .expect("failed to write markdown fixture");

    let output = Command::new(env!("CARGO_BIN_EXE_mdo"))
        .args(["--bare", "--output"])
        .arg(&output_path)
        .arg(&input)
        .output()
        .expect("failed to run mdo");

    assert!(output.status.success(), "mdo failed: {output:?}");

    let html = fs::read_to_string(output_path).expect("failed to read html output");
    assert!(html.contains(r#"class="footnote-reference""#));
    assert!(html.contains(r##"href="#1""##));
    assert!(html.contains(r#"class="footnote-definition""#));
    assert!(html.contains(r#"id="1""#));

    fs::remove_dir_all(dir).expect("failed to clean up temp fixture dir");
}

#[cfg(target_os = "linux")]
#[test]
fn normal_output_respects_umask_for_new_files() {
    let dir = fixture_dir("normal-permissions");
    let input = dir.join("sample.md");
    let output_path = dir.join("sample.html");
    fs::write(&input, "# Permissions\n").expect("failed to write markdown fixture");

    let output = Command::new("sh")
        .arg("-c")
        .arg("umask 022; exec \"$@\"")
        .arg("mdo-test-sh")
        .arg(env!("CARGO_BIN_EXE_mdo"))
        .arg("--output")
        .arg(&output_path)
        .arg(&input)
        .output()
        .expect("failed to run mdo through shell");

    assert!(output.status.success(), "mdo failed: {output:?}");

    let mode = fs::metadata(&output_path)
        .expect("failed to stat html output")
        .permissions()
        .mode()
        & 0o777;
    assert_eq!(mode, 0o644);

    fs::remove_dir_all(dir).expect("failed to clean up temp fixture dir");
}

#[cfg(target_os = "linux")]
#[test]
fn open_output_refuses_precreated_symlink() {
    let dir = fixture_dir("open-symlink");
    let input = dir.join("sample.md");
    let target = dir.join("target.txt");
    fs::write(&input, "# Safe\n\nreplacement").expect("failed to write markdown fixture");
    fs::write(&target, "do not overwrite").expect("failed to write symlink target");

    let output_path = temp_output_for_test(&input);
    fs::create_dir_all(
        output_path
            .parent()
            .expect("temp output should have a parent"),
    )
    .expect("failed to create temp output parent");
    symlink(&target, &output_path).expect("failed to create temp output symlink");

    let fake_bin = dir.join("bin");
    fs::create_dir_all(&fake_bin).expect("failed to create fake bin dir");
    let fake_xdg_open = fake_bin.join("xdg-open");
    fs::write(&fake_xdg_open, "#!/bin/sh\nexit 0\n").expect("failed to write fake xdg-open");
    fs::set_permissions(&fake_xdg_open, fs::Permissions::from_mode(0o700))
        .expect("failed to chmod fake xdg-open");

    let output = Command::new(env!("CARGO_BIN_EXE_mdo"))
        .arg("--open")
        .arg(&input)
        .env("PATH", &fake_bin)
        .output()
        .expect("failed to run mdo");

    assert!(output.status.success(), "mdo failed: {output:?}");
    let target_contents = fs::read_to_string(&target).expect("failed to read symlink target");
    assert_eq!(target_contents, "do not overwrite");
    assert!(
        fs::symlink_metadata(&output_path)
            .expect("failed to stat temp output")
            .file_type()
            .is_symlink(),
        "temp output symlink should not have been replaced"
    );

    fs::remove_file(&output_path).expect("failed to remove temp output symlink");
    fs::remove_dir_all(dir).expect("failed to clean up temp fixture dir");
}

#[cfg(target_os = "linux")]
fn temp_output_for_test(input: &std::path::Path) -> PathBuf {
    let canonical = fs::canonicalize(input).unwrap_or_else(|_| input.to_path_buf());
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    canonical.hash(&mut hasher);
    let hash = hasher.finish();

    let stem = input
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("document");

    std::env::temp_dir()
        .join(format!("mdo-{}", unsafe { libc::geteuid() }))
        .join(format!("{hash:016x}"))
        .join(format!("{stem}.html"))
}
